# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=125)),
                ('start_time', models.TimeField()),
                ('stop_time', models.TimeField()),
                ('points_per_hr', models.DecimalField(decimal_places=3, max_digits=4)),
                ('daytime_rate_factor', models.DecimalField(decimal_places=3, max_digits=4)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=6)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated', '-timestamp'],
            },
        ),
    ]
