# Generated by Django 2.0.6 on 2018-06-25 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_type', '0004_auto_20180606_0908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workcategory',
            name='daytime_rate_factor',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
        migrations.AlterField(
            model_name='workcategory',
            name='points_per_hr',
            field=models.DecimalField(decimal_places=3, max_digits=6),
        ),
    ]
