# Generated by Django 2.0.6 on 2018-08-13 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('work_type', '0005_auto_20180625_0835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workcategory',
            name='daytime_rate_factor',
        ),
        migrations.RemoveField(
            model_name='workcategory',
            name='rate',
        ),
    ]
