# Generated by Django 2.0.5 on 2018-05-31 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0002_auto_20180531_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='comment_needed',
            field=models.BooleanField(default=False),
        ),
    ]
