# Generated by Django 2.0.5 on 2018-05-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0003_reasons_comment_needed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reasons',
            name='max_time',
            field=models.SmallIntegerField(default=12, verbose_name='Hour Time Limit'),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='billable',
            field=models.BooleanField(default=False, verbose_name='Is Billable'),
        ),
        migrations.AlterField(
            model_name='reasons',
            name='reason',
            field=models.CharField(max_length=255, verbose_name='Reason'),
        ),
    ]
