# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-22 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facilities', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reasons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_time', models.DateTimeField()),
                ('work_end_time', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=255, null=True)),
                ('shift', models.CharField(blank=True, max_length=255, null=True)),
                ('reconciled', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.Facilities')),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reasons.Reasons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
