# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='comment',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
