# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-26 02:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='billable',
            field=models.BooleanField(default=False),
        ),
    ]
