# Generated by Django 2.0.5 on 2018-05-31 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0002_timelog_billable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='billable',
        ),
    ]
