# Generated by Django 2.0.5 on 2018-05-31 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_remove_timelog_billable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Comment'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='facility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='facilities.Facilities', verbose_name='Facility'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='reasons.Reasons', verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='reconciled',
            field=models.BooleanField(default=False, verbose_name='Is Reconciled'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='shift',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Entry Date'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='work_end_time',
            field=models.DateTimeField(verbose_name='Work End Time'),
        ),
        migrations.AlterField(
            model_name='timelog',
            name='work_start_time',
            field=models.DateTimeField(verbose_name='Work Start Time'),
        ),
    ]
