# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0003_auto_20171126_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='hours_worked',
        ),
        migrations.AddField(
            model_name='timelog',
            name='work_end_time',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 30, 16, 33, 13, 753861, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
