# Generated by Django 2.0.5 on 2018-05-31 15:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reasons', '0004_auto_20180531_1227'),
        ('facilities', '0002_auto_20180125_2004'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timelog', '0006_auto_20180531_1444'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together={('user', 'reason', 'facility', 'work_start_time', 'work_end_time')},
        ),
    ]
