# Generated by Django 2.0.5 on 2018-05-31 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0007_auto_20180531_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelog',
            unique_together=set(),
        ),
    ]
