# Generated by Django 2.0.5 on 2018-06-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0008_auto_20180531_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='pay_memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Memo'),
        ),
    ]
