# Generated by Django 2.0.6 on 2018-06-22 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0009_timelog_pay_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='timelog',
            name='base_value',
            field=models.IntegerField(default=100),
        ),
    ]
