# Generated by Django 2.0.6 on 2018-06-22 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0010_timelog_base_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timelog',
            name='base_value',
        ),
    ]
