# Generated by Django 2.0.6 on 2018-07-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timelog', '0012_timelog_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelog',
            name='pay',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
